### ISSUE TITLE
Structural Changes for result/response handling.

### ISSUE THREAD

**Issue by samrocksc** [samrocksc/howard#11]
## Expected Behavior
The ability to pass in different types of behavior while expecting a promise in return of data.  On `request`, the goal would be able to modify the request to include things such as headers, even smartly modify the method..  On Response, a postFunction will be created that will allow data to be parsed through in a smart method.

- [ ] The `howard` method should accept a third `config` param that will accept also pre/post plugins.  These can be handed out through withDefaults.
- [ ] The object for `withDefaults` accepts `prePlugin`.
- [ ] The object for `withDefaults acce'ts `postPlugin`.
- [ ] `prePlugin` will identify plugins that will fire on the `request` of data to the server.
- [ ] `postPlugin` will identify plugins that will fire on the `response`.  This can probably be placed on the default howard function.

**Comment by monteslu** [comment]
Rest.js did something like this, but with an interceptor pattern.  Not sure if you're up for that same type of thing, but it might fulfill what you want to accomplish here.
https://github.com/cujojs/rest/blob/master/docs/interceptors.md
